export default  {
    'login': '点击登录',
    'forgetPwd': '点击忘记密码',
    'regist': '点击注册',
    'accounttype':'点击查看账本信息',
    'addaccount':'点击添加账本',
    'dellaccount':'点击删除账本',
    'addbudget':'点击新增预算',
    'account':'点击查看消费类型',
    'find':'点击查看发现',
    'self':'点击查看个人信息',
    'fankuisugg':'点击反馈意见',
    'jyb':'点击记一笔',
    'zjyb':'点击再记一笔',
    'compile':'点击编辑一笔账详情',
    'lookInfo':'点击查看一笔账详情',
    'comsumer':'点击查看消费账户',
    'updating':'点击查看版本',
}